version: 2
jobs:
  build:
    working-directory: ~/website
    docker:
      - image: circleci/node:8.11.0
    steps:
      - checkout
      - run:
          name: setup-env
          command: 'echo "NODE_ENV=production" > .env'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm-install
          command: 'npm install'
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: webpack-build
          command: 'NODE_ENV=production npm run webpack'
      - persist_to_workspace:
          root: .
          paths:
            - dist
  deploy:
    working-directory: ~/website
    docker:
      - image: circleci/node:8.11.0
    steps:
      - run:
          name: install-awscli
          command: |
            sudo apt-get -y -qq update
            sudo apt-get -y -qq install python3.4-dev
            curl -O https://bootstrap.pypa.io/get-pip.py
            sudo python3.4 get-pip.py
            sudo pip install awscli --upgrade
      - attach-workspace:
          at: /tmp/workspace
      - run:
          name: s3-upload
          command: |
            export S3_BUCKET=$( [ $CIRCLE_BRANCH == "production" ] && echo "s3://std-docs.luna-lang.org" || echo "s3://std-docs-staging.luna-lang.org" )
            aws s3 sync /tmp/workspace/dist $S3_BUCKET --delete --acl public-read

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - production
